#!/usr/bin/env bash
# Install nginx web server

# Update package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Replaced teh default nginx landing page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Change ownership of the landing page to the user
sudo chown "$USER":"$USER" /var/www/html/index.html

# Restart Nginx to apply changes
sudo service nginx restart

# Ensure Nginx is listening on port 80
# netcat in scan mode
if ! nc -z localhost 80; then
    echo "Nginx is not listening on port 80. Please check the configuration."
    exit 1
fi

# Display success message
echo "Nginx installed and configured successfully!"
