#!/usr/bin/env bash
# Configuring Nginx server to redirect to another page

# Define the Nginx configuration file path
nginx_conf="/etc/nginx/sites-available/default"

# Use sed to add a location block for /redirect_me with a 301 redirect
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}' "$nginx_conf"

# Reload Nginx to apply the changes
sudo systemctl reload nginx
