#!/usr/bin/env bash
# Configuring Nginx server to redirect to another page

sudo apt-get -y update
sudo apt-get -y install nginx

# Replaced the default nginx landing page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Change ownership of the landing page to the user
sudo chown "$USER":"$USER" /var/www/html/index.html

# Define the Nginx configuration file path
nginx_conf="/etc/nginx/sites-available/default"

# Use sed to add a location block for /redirect_me with a 301 redirect
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}' "$nginx_conf"

# Reload Nginx to apply the changes
sudo systemctl reload nginx
