#!/usr/bin/env bash
# Customize 404 error message

# Ensure Nginx is installed
sudo apt-get -y update
sudo apt-get -y install nginx

# Replaced the default nginx landing page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Change ownership of the landing page to the user
sudo chown "$USER":"$USER" /var/www/html/index.html

# Create a custom HTML file for the 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Define the Nginx configuration file path
nginx_conf="/etc/nginx/sites-available/default"

# Use sed to add a location block for a custom 404 page
sudo sed -i '/server_name _;/a \\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' "$nginx_conf"

# Restart Nginx to apply the changes
sudo service nginx restart

# Display success message
echo "Nginx configured for custom 404 page successfully!"
