#!/usr/bin/env bash
# shellcheck disable=SC2154
# This script configures a new ubuntu machine nginx

# Update the package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Replaced the default nginx landing page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Change ownership of the landing page to the user
sudo chown "$USER":"$USER" /var/www/html/index.html

# Create a custom HTML file for the 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Define the Nginx configuration file path
nginx_conf="/etc/nginx/sites-available/default"

# Use sed to add a location block for a custom 404 page
sudo sed -i '/server_name _;/a \\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' "$nginx_conf"

# Define the custom header configuration
custom_header_config='
    add_header X-Served-By $hostname;
'

# Add the custom header configuration to the Nginx default site configuration
echo "$custom_header_config" | sudo tee -a /etc/nginx/sites-available/default > /dev/null

# Restart Nginx to apply the changes
sudo service nginx restart

# Print a message indicating that the configuration is complete
echo "Nginx has been configured to include custom header X-Served-By with the server's hostname."
