#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server

# Install HAProxy
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get update
apt-get install -y haproxy=2.8.\*

# Configure HAProxy for round-robin load balancing
haproxy_config="\nfrontend web\n
\tbind *:80
\tmode http
\tdefault_backend web_servers

backend web_servers\n
\tbalance roundrobin
\tserver 464202-web-01 54.172.171.23:80 check
\tserver 464202-web-02 54.172.83.49:80 check
"

# Ensure HAProxy can be managed via init script
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy

# Apply HAProxy configuration
echo -e "$haproxy_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAProxy service
# Check if the installation and configuration were successful
if service haproxy restart; then
	echo "HAProxy has been installed and configured for round-robin load balancing."
	echo "Ensure Hostnames for web-01 and web-02 have been set properly on your web servers."
else
	echo "Error: HAProxy installation or configuration failed."
fi
