#!/usr/bin/env bash
# Configure Nginx, serve default page, stop Nginx, wait, start Nginx
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx stop && sleep 1 && service nginx start
